### PR TITLE
Adding the python programs files, to solve.

### PR DESCRIPTION
**Pull request by NitkarshChourasia**
# Nitkarsh Chourasia.

### CODE REVIEW

**Review by NitkarshChourasia — COMMENTED** [review]
# All perfect.

**Comment by NitkarshChourasia** [comment]
# Review it, prince and merge it.

**Comment by NitkarshChourasia** [comment]
mai prince, pricey hu.

**Review by princegupta18 — APPROVED** [review]

**Comment by NitkarshChourasia** [comment]
okay!

**Comment by princegupta18** [comment]
https://www.youtube.com/playlist?list=PLpPXw4zFa0uKKhaSz87IowJnOTzh9tiBk
review this bro

**Comment by NitkarshChourasia** [comment]
Thike...fir bhi code toh karna padega na?

**Pull request merged**
